language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

# lock distro so new future defaults will not break the build
dist: precise

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm

sudo: false

install:
  - COMPOSER_ROOT_VERSION=`git describe --abbrev=0` composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text
